export const translatedSkillSpec = {
	Acrobatics: "акробатика",
	Act: "актёрство",
	Acting: "актёрство",
	Albion: "альбион",
	Alchemist: "алхимик",
	Alcohol: "алкоголь",
	Altdorf: "Альтдорф",
	All: "все",
	Ambosstein: "Амбосштайн",
	Anatomy: "анатомия",
	Animals: "животные",
	"Any Chaos": "любая школа Хаоса",
	"Any color": "любой цвет",
	"Any Color": "любой цвет",
	"any one": "любой",
	any: "любое",
	Any: "любое",
	Apothecary: "аптекарь",
	Aqshy: "Акши",
	Araby: "Арабия",
	"Art Supplies": "художественные принадлежности",
	Art: "искусство",
	Astrology: "астрология",
	Astronomy: "астрономия",
	Azyr: "Азир",
	Bagpipe: "волынка",
	Balalaika: "балалайка",
	Barber: "цирюльник",
	Barge: "баржи",
	Basic: "основное",
	"Battle Tongue": "боевой арго",
	battle: "боевой арго",
	Battle: "боевой арго",
	Beasts: "звери",
	"Black chamber": "Чёрная палата",
	Blackpowder: "пороховое",
	Blacksmith: "кузнец",
	Boatbuilding: "корабел",
	Bounties: "разыскиваемые",
	Bow: "луки",
	Brawling: "кулачное",
	Bretonnian: "бретонский",
	Brewer: "пивовар",
	Brewing: "пивоварение",
	Calligrapher: "каллиграф",
	Calligraphy: "каллиграфия",
	Caravel: "каравеллы",
	Carpenter: "плотник",
	Cartographer: "картограф",
	Cartography: "картография",
	Cavalry: "кавалерийское",
	Celestial: "Школа Небес",
	Chamon: "Шамон",
	Chandler: "свечник",
	Chaos: "Хаос",
	Charms: "мастер талисманов",
	Cheesemonger: "сыровар",
	Chemistry: "химия",
	Classical: "классический",
	Clowning: "клоунада",
	Cog: "когги",
	"Coin stamping": "чеканка монет",
	"Coin Stamping": "чеканка монет",
	Comedy: "комедия",
	Conjuring: "фокусы",
	Cook: "повар",
	Corosion: "коррозия",
	"Crossbow Pistol": "арбалеты",
	Crossbow: "арбалеты",
	Cults: "культы",
	Daemonology: "демонология",
	Dancing: "танец",
	"Dark Magic": "Тёмная магия",
	"Dark tongue": "тёмное наречие",
	"Dark Tongue": "тёмное наречие",
	Demigryph: "демигрифы",
	Dhar: "Дхар",
	Dog: "собаки",
	Dragon: "дракон",
	Dragons: "драконы",
	"Drum or Fife": "барабан или флейта",
	Drum: "барабан",
	Eltharin: "эльтарин",
	Elthárin: "эльтарин",
	Embalmer: "бальзамировщик",
	Engineer: "инженер",
	Engineering: "инженерное дело",
	Engraver: "гравёр",
	Engraving: "гравюра",
	Entangling: "ловчее",
	"Estalian or Tilean": "эсталийский или тилейский",
	Estalian: "эсталийский",
	Explosives: "взрывчатка",
	Farrier: "коновал",
	Fencing: "фехтовальное",
	Fife: "флейта",
	Fight: "бой",
	Firebreathing: "глотание огня",
	Flail: "цепы",
	Folklore: "фольклор",
	"Fortune Telling": "гадания",
	Frigate: "фрегаты",
	Genealogy: "генеалогия",
	Geography: "география",
	Geology: "геология",
	Ghur: "Гарр",
	Ghyran: "Гайран",
	Giants: "великаны",
	Goldsmith: "ювелир",
	Gospodarinyi: "господарский",
	"Great Wolf": "гигантские волки",
	"Grey Order": "Серый Орден",
	Griffon: "грифоны",
	Grumbarth: "грамбарт",
	Guilder: "гильдейцы",
	Gunsmith: "ружейник",
	Harpsichord: "клавесин",
	Harpsicord: "клавесин",
	Heraldry: "геральдика",
	Herbalist: "травник",
	Herbs: "травы",
	Heretics: "еретики",
	History: "история",
	Horn: "рожок",
	Horse: "лошади",
	Hunter: "охотники",
	Hysh: "Хиш",
	Icons: "иконопись",
	Juggling: "жонглирование",
	Khazalid: "кхазалид",
	"Knightly Order": "рыцарский орден",
	Law: "закон",
	Lecture: "лекции",
	Local: "местность",
	Lute: "лютня",
	Lyre: "лира",
	Magic: "магия",
	Magick: "магия",
	Mason: "каменщик",
	Medicine: "медицина",
	Metallurgy: "металлургия",
	Middenland: "Мидденланд",
	Miming: "пантомима",
	Miner: "рудокопы",
	"Mòna’s Marsh Magic": "магия Болотной Моны",
	Mootish: "мутландский",
	Mosaics: "мозаика",
	Necromancy: "некромантия",
	Nehekhara: "Нехекхара",
	Nehekharan: "нехекхарский",
	Nobles: "дворяне",
	Norse: "норс",
	Nuln: "Нульн",
	Painting: "живопись",
	Parry: "парирующее",
	Pegasus: "пегасы",
	Philosophy: "философия",
	Pigeon: "голуби",
	Plants: "растения",
	Playwriting: "драматургия",
	Poetry: "поэзия",
	Poison: "яды",
	Poisoner: "отравитель",
	Poisons: "яд",
	Polearm: "древковое",
	Politics: "политика",
	Printing: "печатник",
	Prophecy: "пророчества",
	Queekish: "квикиш",
	Ranger: "охотники",
	Reikland: "Рейкланд",
	Reikspiel: "рейкшпиль",
	Rhetoric: "риторика",
	Riverways: "судоходные реки",
	"Rope Walking": "хождение по канату",
	Routes: "маршруты",
	Runes: "руны",
	"Rural or Urban": "города или сельская местность",
	Rural: "дикая природа",
	Science: "наука",
	Scout: "разведчики",
	Sculpture: "скульптура",
	Servants: "слуги",
	Shyish: "Шаиш",
	Sight: "зрение",
	Sigmar: "Сигмар",
	Sing: "пение",
	Singing: "пение",
	Sling: "пращи",
	Smell: "нюх",
	Smith: "кузнец",
	Smuggler: "контрабандисты",
	Snake: "змеи",
	Speeches: "речи",
	Spirits: "духи",
	Stirland: "Штирланд",
	Storyteller: "сказительство",
	Storytelling: "сказительство",
	Sylvania: "Сильвания",
	Tailor: "портняжничество",
	Tanner: "дубильщик",
	Taste: "вкус",
	Tattoo: "татуировка",
	Taunt: "подначки",
	Taxes: "налоги",
	"The Empire": "Империя",
	"the Empire": "Империя",
	"the Arts": "искусство",
	Theology: "теология",
	Thief: "воры",
	"Thieves Tongue": "воровской арго",
	Throwing: "метательное",
	Thrown: "метательное",
	Tilean: "тилейский",
	Tinker: "медник",
	Torture: "пытки",
	Touch: "осязание",
	Trolls: "тролли",
	"Two-handed": "двуручное",
	"Two-Handed": "двуручное",
	Ubersreik: "Убершрейк",
	Ulgu: "Улгу",
	"Underground or Urban": "города или подземелья",
	Underground: "подземелья",
	Urban: "города",
	Vagabond: "бродяги",
	Various: "различное",
	Vintner: "винодел",
	Violin: "скрипка",
	Virginal: "вёрджинел",
	Vision: "зрение",
	Warfare: "военное дело",
	Wastelander: "вестерландский",
	Weaving: "ткачество",
	Wissenland: "Виссенланд",
	Witches: "ведьмы",
	Wolfship: "волчьи корабли",
	Wrecks: "кораблекрушения",
	Writing: "писательство",
};

export const translatedSkillExceptions = {
	"Language (Guilder)": "Язык (гильдейский арго)",
	"Language (Magick)": "Язык (магический)",
	"Language (Battle)": "Язык (боевой арго)",
	"Trade (Engineering)": "Ремесло (инженер)",
	"Ranged (Engineering)": "Стрельба (инженерное)",
};

export const translatedTalentSpec = {
	//"Average": "Средний",
	Acid: "едкое",
	Animals: "животные",
	"Any Chaos": "любая школа Хаоса",
	any: "любое",
	Any: "любое",
	"Apothecary or Herbalist": "аптекарь или травник",
	Apothecary: "аптекарь",
	Average: "Заурядная",
	"Bailiffs, Lawyers": "бейлифы, законники",
	Beastmen: "зверолюды",
	Beasts: "Школа Зверей",
	Bounties: "разыскиваемые",
	Broken: "приручённый",
	Celestial: "Школа Небес",
	Challenging: "Серьёзная",
	Chaos: "Школа Хаоса",
	"Choose one": "выберите одно",
	"Choose two": "выберите два",
	Claws: "когти",
	Coastal: "побережья",
	Criminals: "преступники",
	Cultists: "духовенство",
	Daemonology: "Школа Демонологии",
	Death: "Школа Смерти",
	Deity: "божество",
	Difficult: "Трудная",
	Difficulty: "Сложность",
	Disease: "болезни",
	Drive: "тягловый",
	Easy: "Лёгкая",
	Elves: "эльфы",
	Engineer: "инженер",
	Engineering: "инженерное дело",
	Enormous: "Огромный",
	Everything: "все",
	Fangs: "клыки",
	Fetch: "апорт",
	Fire: "Школа Огня",
	Futile: "Тщетная",
	Gas: "ядовитое",
	Greenskins: "зеленокожие",
	Guard: "сторожевой",
	Guilders: "гильдейцы",
	Hard: "Тяжёлая",
	Heavens: "Школа Небес",
	Hedgecraft: "Школа Знахарства",
	Herbalist: "травник",
	Herbs: "травы",
	Heretics: "еретики",
	Hide: "шкура",
	Impossible: "Отчаянная",
	Intruders: "нарушители",
	"Itching Pox": "сыпучая чесотка",
	Large: "Большой",
	Law: "закон",
	Life: "Школа Жизни",
	Light: "Школа Света",
	Little: "Маленький",
	Living: "живые",
	local: "местность",
	Local: "местность",
	Major: "мощный",
	Marshes: "болота",
	Medicine: "медицина",
	Metal: "Школа Металла",
	Minor: "слабый",
	Moderate: "сильный",
	Monsters: "чудовища",
	Monstrous: "Чудовищный",
	Mount: "верховой",
	Necromancy: "Школа Некромантии",
	Nobles: "дворяне",
	nobles: "дворяне",
	Nurgle: "Школа Нургла",
	"Orcs and Goblins": "орки и гоблины",
	Outlaws: "разбойники",
	Outsiders: "чужаки",
	"Packer's Pox": "корняжная оспа",
	Poison: "яд",
	Rats: "крысы",
	"Ratte Fever": "крысиная лихорадка",
	Riverwardens: "речные стражники",
	Rivals: "соперники",
	"Road Wardens": "дорожные стражники",
	Rocky: "горы",
	Scales: "чешуя",
	Scholar: "книгочеи",
	Servants: "слуги",
	Shadow: "Школа Теней",
	Sight: "зрение",
	Sigmarite: "сигмариты",
	Sigmarites: "сигмариты",
	Skaven: "скавены",
	Slaanesh: "Школа Слаанеша",
	Small: "Небольшой",
	Soldiers: "солдаты",
	Strangers: "незнакомцы",
	Target: "цель",
	"Taste or Touch": "вкус или осязание",
	Taste: "вкус",
	Tentacles: "щупальца",
	"the Poor": "бедняки",
	"the Rich, Beastmen": "богатеи, зверолюды",
	Theology: "теология",
	Thieves: "воры",
	"Thin People": "худые индивиды",
	Tiny: "Крохотный",
	Type: "разные",
	Tzeentch: "Школа Тзинтча",
	Undead: "нежить",
	Various: "варьируется",
	Venom: "яд",
	"Very Easy": "Элементарная",
	"Very Hard": "Безумная",
	War: "боевой",
	Watchmen: "стражники",
	Witch: "Школа Ведьмовства",
	Witchcraft: "Школа Ведьмовства",
	Witchery: "Школа Ведьмовства",
	Witches: "ведьмы",
	Wreckers: "побережники",
};

export const translatedDuration = {
	seconds: "секунд",
	minutes: "минут",
	hours: "часов",
	days: "дней",
	weeks: "недель",
};

export const translatedHitLocation = {
	Arm: "Рука",
	Body: "Торс",
	Ear: "Ухо",
	Finger: "Палец",
	Foot: "Ступня",
	Head: "Голова",
	Leg: "Нога",
	Nose: "Нос",
	Teeth: "Зубы",
	Tongue: "Язык",
};

export const translatedGender = {
	Varies: "Различный",
	Male: "Мужской",
	Female: "Женский",
};

export const translatedSpecies = {
	Dwarf: "Гном",
	Elf: "Эльф",
	"High Elf": "Высший эльф",
	"Wood Elf": "Лесной эльф",
	Halfling: "Полурослик",
	Gnome: "Карлик",
	Basilisk: "Василиск",
	Boar: "Кабан",
	"Bog Octopus": "Болотный осьминог",
	"Bray Shaman": "Ревучий шаман",
	Daemon: "Демон",
	Demigryph: "Демигриф",
	Demon: "Демон",
	Dog: "Собака",
	Dragon: "Дракон",
	Fenbeast: "Торфяное чудище",
	Fimir: "Фимир",
	Ghoul: "Упырь",
	Giant: "Великан",
	Goblin: "Гоблин",
	Gor: "Гор",
	Greenskin: "Зеленокожий",
	Griffon: "Грифон",
	Hippogryph: "Гиппогриф",
	Horse: "Лошадь",
	Human: "Человек",
	Hydra: "Гидра",
	Jabberslythe: "Бормохват",
	Manticore: "Мантикора",
	Minotaur: "Минотавр",
	Ogre: "Огр",
	Pegasus: "Пегас",
	Pigeon: "Голубь",
	Rat: "Крыса",
	Skaven: "Скавен",
	Squig: "Сквиг",
	Troll: "Тролль",
	Undead: "Нежить",
	Ungor: "Унгор",
	Wolf: "Волк",
	Spider: "Паук",
	"Snake-Like": "Змееподобный",
	"Spider-Like": "Паукоподобный",
	Wyvern: "Виверна",
};

export const translatedCareerClass = {
	Academic: "Книгочей",
	Academics: "Книгочеи",
	Burgher: "Бюргер",
	Burghers: "Бюргеры",
	Courtier: "Придворный",
	Courtiers: "Придворные",
	Peasant: "Крестьянин",
	Peasants: "Крестьяне",
	Ranger: "Странник",
	Rangers: "Странники",
	Riverfolk: "Речники",
	Rogue: "Шельма",
	Rogues: "Шельмы",
	Warrior: "Воин",
	Warriors: "Воины",
};

export const translatedSpellRange = {
	You: "персонаж",
	Touch: "касание",
	"Willpower yards": "Сила воли ярдов",
	"Willpower Yards": "Сила воли ярдов",
	"Willpower Bonus yards": "Рейтинг силы воли ярдов",
	"Willpower bonus yards": "Рейтинг силы воли ярдов",
	"Initiative yards": "Инициатива ярдов",
	"Initiative Bonus miles": "Рейтинг инициативы миль",
	"Intelligence Bonus yards": "Рейтинг интеллекта ярдов",
	"Willpower Bonus miles": "Рейтинг силы воли миль",
	"Willpower Bonus Miles": "Рейтинг силы воли миль",
	"Willpower miles": "Сила воли миль",
	"1 yard": "1 ярд",
	Special: "Особая",
	"AoE (Willpower yards)": "Область воздействия (Сила воли ярдов)",
	"AoE (Intelligence yards)": "Область воздействия (Интеллект ярдов)",
	"Half Intelligence yards or Touch": "Интеллект / 2 ярдов или касание",
	"Willpower / 2 yards": "Сила воли / 2 ярдов",
	"Half Willpower yards": "Сила воли / 2 ярдов",
	"Initiative / 2 yards": "Инициатива / 2 ярдов",
	"Half Initiative yards": "Инициатива / 2 ярдов",
	"AoE (Willpower Bonus yards)":
		"Область воздействия (Рейтинг силы воли ярдов)",
	"100 yards": "100 ярдов",
	"AoE (Fellowship yards)": "Область воздействия (Харизма ярдов)",
	"Line of sight": "Прямая видимость",
	"2 * Fellowship Bonus yards": "2 * (Рейтинг харизмы ярдов)",
	"You or Touch": "Персонаж или касание",
	"Intelligence yards": "Интеллект ярдов",
	"6 yards": "6 ярдов",
	"Fellowship yards": "Харизма ярдов",
	"Fellowship Bonus yards": "Рейтинг харизмы ярдов",
	"Initiative Bonus Miles": "Рейтинг инициативы миль",
	Self: "Персонаж",
	"See text": "смотри текст",
	"24 yds": "24 ярда",
	"36 yds": "36 ярдов",
	"Fellowship Yards": "Харизма ярдов",
};

export const translatedSpellTarget = {
	You: "Персонаж",
	Special: "Особая",
	"AoE (Willpower Bonus yards)":
		"Область воздействия (Рейтинг силы воли ярдов)",
	"AoE (see description)": "Область воздействия (см. описание)",
	"AoE (Special)": "Область воздействия (особая)",
	"AoE (Initiative Bonus yards)":
		"Область воздействия (Рейтинг инициативы ярдов)",
	"AoE (Fellowship Bonus yards)": "Область воздействия (Рейтинг харизмы ярдов)",
	"AoE (a single location)": "Область воздействия (выбранное место)",
	"AoE (maximum, Willpower Bonus yards across)":
		"Область воздействия (не более Рейтинг силы воли ярдов в поперечнике)",
	"see description": "смотри описание",
	"a single location": "выбранное место",
	"Willpower Bonus yards across maximum":
		"не более Рейтинг силы воли ярдов в поперечнике",
	"1 (maximum)": "1 (максимум)",
	"2 × Initiative Bonus or Initiative Bonus Duration: Instant":
		"2 * Рейтинг инициативы или Рейтинг инициативы",
	"2 × Initiative Bonus or Initiative Bonus":
		"2 * Рейтинг инициативы или Рейтинг инициативы",
	"1 Forge": "1 кузнечный горн",
	"1 fire": "1 огонь",
	"1 with AoE (Willpower Bonus yards)":
		"1 с областью воздействия (Рейтинг силы воли ярдов)",
	"You or 1 (maximum)": "персонаж или 1 (максимум)",
	"1 object": "1 объект",
	"1 weapon": "1 оружие",
	special: "особая",
	"1 object of 1 Encumbrance": "1 объект не более 1 Вес",
	"Willpower Bonus yards": "Рейтинг силы воли ярдов",
	"Fellowship Bonus": "Рейтинг харизмы ярдов",
	"Fellowship Bonus yards": "Рейтинг харизмы ярдов",
	"Initiative Bonus yards": "Рейтинг инициативы ярдов",
	"Initiative yards": "Инициатива ярдов",
	"2 * Willpower Bonus yards": "2 * Рейтинг силы воли ярдов",
	"4 * AoE (Willpower Bonus yards)":
		"4 * Область воздействия (Рейтинг силы воли ярдов)",
	"Willpower yards": "Сила воли ярдов",
	"Intelligence Bonus allies": "Рейтинг интеллекта ярдов",
	"8 yards": "8 ярдов",
	"Fellowship Bonus allies": "Рейтинг харизмы союзников",
	"Fellowship yards": "Харизма ярдов",
	"Line of Sight": "Прямая видимость",
	"Any ally": "Любой союзник",
	"See text": "смотри текст",
	"Fellowship Bonus Yards": "Рейтинг харизмы ярдов",
};

export const translatedSpellDuration = {
	Instant: "мгновенная",
	Special: "особая",
	"Toughness Bonus Rounds": "Рейтинг выносливости раундов",
	"Willpower Bonus Rounds": "Рейтинг силы воли раундов",
	"Willpower Bonus rounds": "Рейтинг силы воли раундов",
	"Willpower Bonus Rounds+": "Рейтинг силы воли раундов +",
	"Willpower Bonus days": "Рейтинг силы воли дней",
	"Willpower Bonus Days": "Рейтинг силы воли дней",
	"Willpower Bonus hours": "Рейтинг силы воли часов",
	"Toughness Bonus hours": "Рейтинг выносливости часов",
	"Toughness Bonus minutes": "Рейтинг выносливости часов",
	"Willpower minutes": "Сила воли минут",
	"Willpower Minutes": "Сила воли минут",
	"Willpower Bonus minutes": "Рейтинг силы воли минут",
	"Willpower Days": "Сила воли дней",
	"Willpower days": "Сила воли дней",
	"1 Round": "1 раунд",
	"1 round": "1 раунд",
	"3 rounds": "3 раунда",
	"6 rounds": "6 раунда",
	"Initiative Bonus Rounds": "Рейтинг инициативы раундов",
	"Initiative Bonus rounds": "Рейтинг инициативы раундов",
	"Intelligence minutes": "Интеллект минут",
	"Target’s Intelligence Bonus Rounds": "Рейтинг интеллекта цели раундов",
	"Intelligence Bonus minutes": "Рейтинг интеллекта минут",
	"Until the next sunrise": "до рассвета",
	"Until sunrise - до рассвета": "до рассвета",
	"Initiative Bonus minutes": "Рейтинг инициативы минут",
	"1 hour": "1 час",
	"1 day": "1 день",
	"Fellowship Bonus rounds": "Рейтинг харизмы раундов",
	"Fellowship Bonus minutes": "Рейтинг харизмы минут",
	"Willpower Bonus hours, days, weeks, or months":
		"Рейтинг силы воли часов, дней, недель или месяцев",
	"Willpower Bonus minutes or days": "Рейтинг силы воли минут или дней",
	"Initiative minutes": "Инициатива минут",
	"Strength Bonus rounds": "Рейтинг силы раундов",
	"2 * Willpower Bonus rounds": "2 * Рейтинг силы воли раундов",
	"Willpower * 1d10 minutes": "Сила воли * 1d10 минут",
	"1d10 hours": "1d10 часов",
	"Willpower Bonus years": "Сила воли лет",
	"6 Rounds": "6 раундов",
	"Fellowship Bonus Rounds": "Рейтинг харизмы раундов",
	"1 Hour": "1 час",
	"Fellowship Bonus Hours (Special)": "Рейтинг харизмы часов (особое)",
	"Fellowship Bonus Hours": "Рейтинг харизмы часов",
	"Fellowship Bonus Minutes": "Рейтинг харизмы минут",
	"Agility Bonus Rounds": "Рейтинг проворства раундов",
	"Fellowship bonus Rounds": "Рейтинг харизмы раундов",
	"4 Rounds": "4 раунда",
	"3 Rounds": "3 раунда",
	Immediate: "Мгновенно",
};

export const translatedSpellDamage = {
	"Willpower Bonus": "Рейтинг силы воли",
	"Toughness Bonus": "Рейтинг выносливости",
};

export const translatedGods = {
	Shallya: "Шалия",
	Ulric: "Ульрик",
	Taal: "Таал",
	Sigmar: "Сигмар",
	Ranald: "Ранальд",
	Rhya: "Райя",
	Morr: "Морр",
	Myrmidia: "Мирмидия",
	Manann: "Мананн",
	Verena: "Верена",
};

export const translatedExceptions = {
	"Craftsman (Engineer)": "Умелец (инженер)",
	"Language (Battle)": "Язык (боевой арго)",
	"Language (Magick)": "Язык (магический)",
	"Lore (Engineer)": "Знание (инженерное дело)",
	"Ranged (Engineering)": "Стрельба (инженерное)",
	"Savant (Engineering)": "Кладезь знаний (инженерное дело)",
	"Trade (Engineer)": "Ремесло (инженер)",
};
