export const translatedSkill = {
	// Core Rulebook
	"Animal Care": "Обращение с животными",
	"Animal Training": "Дрессировка",
	"Art": "Искусство",
	"Athletics": "Атлетика",
	"Bribery": "Подкуп",
	"Channelling": "Концентрация",
	"Charm Animal": "Усмирение животных",
	"Charm": "Обаяние",
	"Climb": "Лазание",
	"Consume Alcohol": "Кутёж",
	"Cool": "Хладнокровие",
	"Dodge": "Уклонение",
	"Drive": "Вождение",
	"Endurance": "Стойкость",
	"Entertain": "Артистизм",
	"Evaluate": "Оценка",
	"Gamble": "Азартные игры",
	"Gossip": "Сплетничество",
	"Haggle": "Торговля",
	"Heal": "Лечение",
	"Intimidate": "Запугивание",
	"Intuition": "Интуиция",
	"Language": "Язык",
	"Leadership": "Лидерство",
	"Lore": "Знание",
	"Melee": "Рукопашный бой",
	"Navigation": "Ориентирование",
	"Outdoor Survival": "Выживание",
	"Perception": "Наблюдательность",
	"Perform": "Сценическое искусство",
	"Pick Lock": "Взлом",
	"Play": "Музицирование",
	"Pray": "Молитвословие",
	"Ranged": "Стрельба",
	"Research": "Книжные изыскания",
	"Ride": "Верховая езда",
	"Row": "Гребля",
	"Sail": "Хождение под парусом",
	"Secret Signs": "Тайные знаки",
	"Set Trap": "Обращение с ловушками",
	"Sleight of Hand": "Ловкость рук",
	"Stealth": "Скрытность",
	"Swim": "Плавание",
	"Track": "Выслеживание",
	"Trade": "Ремесло",
	"Sigmarite": "сигмариты",
	"Sigmarites": "сигмариты",
	"Greenskins": "зеленокожие"
};

export const translatedSpec = {
	// Core Rulebook
	"Acrobatics": "акробатика",
	"Act": "актёрство",
	"Acting": "актёрство",
	"Albion": "альбион",
	"Alcohol": "алкоголь",
	"any": "любое",
	"Any": "любое",
	"Apothecary": "аптекарь",
	"Aqshy": "Акши",
	"Art Supplies": "художественные принадлежности",
	"Art": "искусство",
	"Astrology": "астрология",
	"Azyr": "Азир",
	"Bagpipe": "волынка",
	"Barge": "баржи",
	"Basic": "основное",
	"Battle Tongue": "боевой арго",
	"Blackpowder": "пороховое",
	"Bounties": "разыскиваемые",
	"Bow": "луки",
	"Brawling": "кулачное",
	"Bretonnian": "бретонский",
	"Brewer": "пивовар",
	"Calligrapher": "каллиграф",
	"Calligraphy": "каллиграфия",
	"Caravel": "каравеллы",
	"Carpenter": "плотник",
	"Cartography": "картография",
	"Cavalry": "кавалерийское",
	"Chamon": "Шамон",
	"Chandler": "свечник",
	"Chaos": "Хаос",
	"Cheesemonger": "сыровар",
	"Chemistry": "химия",
	"Classical": "классический",
	"Clowning": "клоунада",
	"Cog": "когги",
	"Comedy": "комедия",
	"Cook": "повар",
	"Corosion": "коррозия",
	"Crossbow": "арбалеты",
	"Dancing": "танец",
	"Demigryph": "демигрифы",
	"Demigryph": "демигрифы",
	"Dhar": "Дхар",
	"Dog": "собаки",
	"Dragons": "драконы",
	"Drum or Fife": "барабан или флейта",
	"Elthárin": "эльтарин",
	"Embalmer": "бальзамировщик",
	"Engineer": "инженер",
	"Engineering": "инженерное дело",
	"Engraver": "гравёр",
	"Engraving": "гравюра",
	"Entangling": "ловчее",
	"Estalian": "эсталийский",
	"Explosives": "взрывчатка",
	"Farrier": "коновал",
	"Fencing": "фехтовальное",
	"Firebreathing": "глотание огня",
	"Flail": "цепы",
	"Fortune Telling": "гадания",
	"Frigate": "фрегаты",
	"Geology": "геология",
	"Ghur": "Гарр",
	"Ghyran": "Гайран",
	"Giants": "великаны",
	"Gospodarinyi": "господарский",
	"Great Wolf": "гигантские волки",
	"Grey Order": "Серый Орден",
	"Griffon": "грифоны",
	"Grumbarth": "грамбарт",
	"Guilder": "гильдейцы",
	"Gunsmith": "ружейник",
	"Harpsichord": "клавесин",
	"Heraldry": "геральдика",
	"Herbalist": "травник",
	"Heretics": "еретики",
	"History": "история",
	"Horn": "рожок",
	"Horse": "лошади",
	"Hysh": "Хиш",
	"Icons": "иконопись",
	"Juggling": "жонглирование",
	"Khazalid": "кхазалид",
	"Knightly Order": "рыцарский орден",
	"Law": "закон",
	"Local": "местность",
	"Lute": "лютня",
	"Lyre": "лира",
	"Magick": "магия",
	"Medicine": "медицина",
	"Metallurgy": "металлургия",
	"Miming": "пантомима",
	"Miner": "рудокопы",
	"Mootish": "мутландский",
	"Mosaics": "мозаика",
	"Norse": "норс",
	"Nuln": "Нульн",
	"Painting": "живопись",
	"Parry": "парирующее",
	"Pegasus": "пегасы",
	"Pigeon": "голуби",
	"Plants": "растения",
	"Poison": "яды",
	"Polearm": "древковое",
	"Politics": "политика",
	"Printing": "печатник",
	"Prophecy": "пророчества",
	"Queekish": "квикиш",
	"Ranger": "охотники",
	"Reikland": "Рейкланд",
	"Reikspiel": "рейкшпиль",
	"Riverways": "судоходные реки",
	"Rope Walking": "хождение по канату",
	"Routes": "маршруты",
	"Rural": "дикая природа",
	"Science": "наука",
	"Scout": "разведчики",
	"Sculpture": "скульптура",
	"Servants": "слуги",
	"Shyish": "Шаиш",
	"Sight": "зрение",
	"Sigmar": "Сигмар",
	"Singing": "пение",
	"Sling": "пращи",
	"Smell": "нюх",
	"Smith": "кузнец",
	"Snake": "змеи",
	"Speeches": "речи",
	"Storyteller": "сказительство",
	"Storytelling": "сказительство",
	"Tanner": "дубильщик",
	"Taste": "вкус",
	"Tattoo": "татуировка",
	"Taunt": "подначки",
	"The Empire": "Империя",
	"Theology": "теология",
	"Thief": "воры",
	"Thieves Tongue": "воровской арго",
	"Throwing": "метательное",
	"Thrown": "метательное",
	"Tilean": "тилейский",
	"Touch": "осязание",
	"Trolls": "тролли",
	"Two-handed": "двуручное",
	"Two-Handed": "двуручное",
	"Ulgu": "Улгу",
	"Underground": "подземелья",
	"Urban": "города",
	"Vagabond": "бродяги",
	"Various": "различное",
	"Vintner": "винодел",
	"Violin": "скрипка",
	"Vision": "зрение",
	"Warfare": "военное дело",
	"Wastelander": "вестерландский",
	"Weaving": "ткачество",
	"Wolfship": "волчьи корабли",
	"Wrecks": "кораблекрушения",
	"Writing": "писательство"
};

export const translatedExceptions = {
	"Language (Guilder)": "Язык (гильдейский арго)",
	"Language (Magick)": "Язык (магический)",
	"Language (Battle)": "Язык (боевой арго)",
	"Trade (Engineering)": "Ремесло (инженер)",
	"Ranged (Engineering)": "Стрельба (инженерное)"
};

export const translatedTalent = {
	// Core Rulebook
	"Accurate Shot": "Точный выстрел",
	"Accute Sense": "Обострённое восприятие",
	"Acute Sense": "Обострённое восприятие",
	"Acute": "Обострённое",
	"Aethyric Attunement": "Эфирный унисон",
	"Alley Cat": "Бродячий кот",
	"Ambidextrous": "Амбидекстр",
	"Animal Affinity": "Сродство с животными",
	"Arcane Magic": "Школа магии",
	"Argumentative": "Спорщик",
	"Armour": "Броня",
	"Artistic": "Искусник",
	"Attractive": "Привлекательность",
	"Battle Rage": "Боевая ярость",
	"Beat Blade": "Батман",
	"Beneath Notice": "Простолюдин",
	"Berserk Charge": "Яростный натиск",
	"Blather": "Трёп",
	"Bless": "Благословение",
	"Bookish": "Книжный червь",
	"Break and Enter": "Взлом с проникновением",
	"Breath": "Дыхание",
	"Briber": "Взяткодатель",
	"Cardsharp": "Картёжник",
	"Careful Strike": "Выверенное попадание",
	"Carouser": "Заядлый кутила",
	"Cat-tongued": "Витийство",
	"Catfall": "Кошачья лёгкость",
	"Chaos Magic": "Магия Хаоса",
	"Combat Aware": "Бдительность",
	"Combat Master": "Бывалый воин",
	"Combat Reflexes": "Быстрая реакция",
	"Commanding Presence": "Аура величия",
	"Concoct": "Походный рецепт",
	"Contortionist": "Гуттаперчевость",
	"Coolheaded": "Самообладание",
	"Crack the Whip": "Щелчок кнутом",
	"Craftsman": "Умелец",
	"Criminal": "Преступник",
	"Deadeye Shot": "Меткий выстрел",
	"Dealmaker": "Коммерсант",
	"Detect Artefact": "Распознание артефакта",
	"Diceman": "Игрок в кости",
	"Dirty Fighting": "Грязные приёмы",
	"Disarm": "Разоружение",
	"Distract": "Отвлекающий манёвр",
	"Doomed": "Роковое Пророчество",
	"Drilled": "Строевая подготовка",
	"Dual Wielder": "Двойная атака",
	"Embezzle": "Расхититель",
	"Enclosed Fighter": "Тесный контакт",
	"Etiquette": "Этикет",
	"Fast Hands": "Быстрые руки",
	"Fast Shot": "Быстрый выстрел",
	"Fearless": "Бесстрашие",
	"Feint": "Финт",
	"Field Dressing": "Полевая перевязка",
	"Fisherman": "Рыбак",
	"Flagellant": "Флагеллант",
	"Flee!": "Поспешное бегство",
	"Fleet Footed": "Быстрые ноги",
	"Flight": "Полёт",
	"Frenzy": "Ярость",
	"Frightening": "Устрашающий вид",
	"Furious Assault": "Свирепый натиск",
	"Gregarious": "Общительность",
	"Gunner": "Стрелковая подготовка",
	"Hardy": "Здоровяк",
	"Hatred": "Ненависть",
	"Holy Hatred": "Праведный гнев",
	"Holy Visions": "Видения свыше",
	"Hunter's Eye": "Охотничье чутьё",
	"Impassioned Zeal": "Страстное рвение",
	"Implacable": "Суровый",
	"In-fighter": "Полный контакт",
	"Inspiring": "Воодушевление",
	"Instinctive Diction": "Безупречная дикция",
	"Invoke": "Божественное вмешательство",
	"Iron Jaw": "Стальная челюсть",
	"Iron Will": "Железная воля",
	"Jump Up": "Подскок",
	"Kingpin": "Большая шишка",
	"Lightning Reflexes": "Молниеносная реакция",
	"Linguistics": "Полиглот",
	"Lip Reading": "Чтение по губам",
	"Luck": "Фортуна",
	"Magic Resistance": "Устойчивость к магии",
	"Magical Sense": "Магическое чутьё",
	"Magnum Opus": "Magnum Opus",
	"Marksman": "Меткость",
	"Master of Disguise": "Мастер перевоплощения",
	"Master Orator": "Ритор",
	"Master Tradesman": "Мастер своего дела",
	"Menacing": "Грозный вид",
	"Mimic": "Имитатор",
	"Night Vision": "Сумеречное зрение",
	"Nimble Fingered": "Ловкие пальцы",
	"Noble Blood": "Благородная кровь",
	"Nose for Trouble": "Чутьё на неприятности",
	"Numismatics": "Нумизмат",
	"Old Salt": "Морской волк",
	"Orientation": "Чувство направления",
	"Panhandle": "Жалобный вид",
	"Perfect Pitch": "Абсолютный слух",
	"Petty Magic": "Простейшая магия",
	"Pharmacist": "Фармацевт",
	"Pilot": "Рулевой",
	"Public Speaker": "Оратор",
	"Pure Soul": "Духовная чистота",
	"Rapid Reload": "Быстрая перезарядка",
	"Reaction Strike": "Упреждающий удар",
	"Read/Write": "Грамотность",
	"Relentless": "Непреклонность",
	"Resistance": "Устойчивость",
	"Resolute": "Целеустремлённость",
	"Reversal": "Рокировка",
	"Riposte": "Рипост",
	"River Guide": "Знаток рек",
	"Robust": "Живучесть",
	"Roughrider": "Выездка",
	"Rover": "Скиталец",
	"Savant": "Кладезь знаний",
	"Savvy": "Смекалка",
	"Scale Sheer Surface": "Цепкость",
	"Schemer": "Интриган",
	"Sea Legs": "Мореплаватель",
	"Seasoned Traveller": "Бывалый путешественник",
	"Second Sight": "Второе зрение",
	"Secret Identity": "Альтер эго",
	"Shadow": "Тень",
	"Sharp": "Проницательность",
	"Sharpshooter": "Отличный стрелок",
	"Shieldsman": "Щитоносец",
	"Sixth Sense": "Шестое чувство",
	"Slayer": "Убийца чудовищ",
	"Small": "Небольшой",
	"Sniper": "Снайпер",
	"Speedreader": "Скорочтение",
	"Sprinter": "Бегун",
	"Step Aside": "Разрыв дистанции",
	"Stone Soup": "Каменный суп",
	"Stout-hearted": "Отважное сердце",
	"Strider": "Ходок",
	"Strike Mighty Blow": "Могучий удар",
	"Strike to Injure": "Безжалостный удар",
	"Strike to Stun": "Ошеломляющий удар",
	"Strong Back": "Сильная спина",
	"Strong Legs": "Сильные ноги",
	"Strong Swimmer": "Отличный пловец",
	"Strong-minded": "Твёрдость духа",
	"Sturdy": "Бугай",
	"Suave": "Учтивость",
	"Super Numerate": "Счетовод",
	"Supportive": "Услужливость",
	"Sure Shot": "Верный выстрел",
	"Surgery": "Хирург",
	"Tenacious": "Упрямство",
	"Tinker": "Мастер на все руки",
	"Tower of Memories": "Башня памяти",
	"Trapper": "Ловчий",
	"Trick Riding": "Лихой наездник",
	"Tunnel Rat": "Тоннельная крыса",
	"Unshakable": "Стреляный боец",
	"Very Resilient": "Закалка",
	"Very Strong": "Силач",
	"War Leader": "Командир",
	"War Wizard": "Боевой маг",
	"Warrior Born": "Прирождённый воин",
	"Waterman": "Речной волк",
	"Wealthy": "Богач",
	"Weapon": "Оружие",
	"Well-prepared": "Запасливость",
	"Witch!": "Ведьма"
};

export const translatedSpecification = {
	//"Average": "Средний",
	"Acid": "едкое",
	"Any Chaos": "любая школа Хаоса",
	"Average": "Заурядная",
	"Bailiffs, Lawyers": "бейлифы, законники",
	"Beasts": "Школа Зверей",
	"Broken": "приручённый",
	"Challenging": "Серьёзная",
	"Chaos": "Школа Хаоса",
	"Choose one": "выберите одно",
	"Choose two": "выберите два",
	"Coastal": "побережья",
	"Daemonology": "Школа Демонологии",
	"Death": "Школа Смерти",
	"Difficult": "Трудная",
	"Difficulty": "Сложность",
	"Drive": "тягловый",
	"Easy": "Лёгкая",
	"Elves": "эльфы",
	"Enormous": "Огромный",
	"Everything": "все",
	"Fangs": "клыки",
	"Fetch": "апорт",
	"Fire": "Школа Огня",
	"Futile": "Тщетная",
	"Gas": "ядовитое",
	"Greenskins": "зеленокожие",
	"Guard": "сторожевой",
	"Hard": "Тяжёлая",
	"Heavens": "Школа Небес",
	"Hedgecraft": "Школа Знахарства",
	"Impossible": "Отчаянная",
	"Itching Pox": "сыпучая чесотка",
	"Large": "Большой",
	"Life": "Школа Жизни",
	"Light": "Школа Света",
	"Little": "Маленький",
	"Living": "живые",
	"Major": "мощный",
	"Metal": "Школа Металла",
	"Minor": "слабый",
	"Moderate": "сильный",
	"Monstrous": "Чудовищный",
	"Mount": "верховой",
	"Necromancy": "Школа Некромантии",
	"Packer's Pox": "корняжная оспа",
	"Poison": "Яд",
	"Nurgle": "Школа Нургла",
	"Ratte Fever": "крысиная лихорадка",
	"Scales": "чешуя",
	"Shadow": "Школа Теней",
	"Sigmarite": "сигмариты",
	"Sigmarites": "сигмариты",
	"Slaanesh": "Школа Слаанеша",
	"Small": "Небольшой",
	"the Rich, Beastmen": "богатеи, зверолюды",
	"Thin People": "худые индивиды",
	"Tiny": "Крохотный",
	"Type": "разные",
	"Various": "варьируется",
	"Venom": "Яд",
	"Very Easy": "Элементарная",
	"Very Hard": "Безумная",
	"War": "боевой",
	"Witch": "Школа Ведьмовства",
	"Witchcraft": "Школа Ведьмовства",
	"Target": "Цель",
	"Thieves": "воры"
};

export const translatedDuration = {
	seconds: "секунд",
	minutes: "минут",
	hours: "часов",
	days: "дней",
	weeks: "недель"
};

export const translatedGender = {
	Varies: "Различный",
	Male: "Мужской",
	Female: "Женский"
};

export const translatedHitLocation = {
	Arm: "Рука",
	Body: "Торс",
	Head: "Голова",
	Leg: "Нога"
};

export const translatedCareerClass = {
	Academics: "Книгочеи",
	Burgher: "Бюргеры",
	Courtier: "Придворные",
	Peasants: "Крестьяне",
	Ranger: "Странники",
	Riverfolk: "Речники",
	Rogues: "Шельмы",
	Warrior: "Воины"
};

export const translatedSpellRange = {
	"You": "персонаж",
	"Touch": "касание",
	"Willpower yards": "Сила воли ярдов",
	"Willpower Yards": "Сила воли ярдов",
	"Willpower Bonus yards": "Рейтинг силы воли ярдов",
	"Willpower bonus yards": "Рейтинг силы воли ярдов",
	"Initiative yards": "Инициатива ярдов",
	"Initiative Bonus miles": "Рейтинг инициативы миль",
	"Intelligence Bonus yards": "Рейтинг интеллекта ярдов",
	"Willpower Bonus miles": "Рейтинг силы воли миль",
	"Willpower Bonus Miles": "Рейтинг силы воли миль",
	"Willpower miles": "Сила воли миль",
	"1 yard": "1 ярд",
	"Special": "Особая",
	"AoE (Willpower yards)": "Область воздействия (Сила воли ярдов)",
	"AoE (Intelligence yards)": "Область воздействия (Интеллект ярдов)",
	"Half Intelligence yards or Touch": "Интеллект / 2 ярдов или касание",
	"Willpower / 2 yards": "Сила воли / 2 ярдов",
	"Half Willpower yards": "Сила воли / 2 ярдов",
	"Initiative / 2 yards": "Инициатива / 2 ярдов",
	"Half Initiative yards": "Инициатива / 2 ярдов",
	"AoE (Willpower Bonus yards)": "Область воздействия (Рейтинг силы воли ярдов)",
	"AoE (Willpower yards)": "Область воздействия (Сила воли ярдов)",
	"100 yards": "100 ярдов",
	"AoE (Fellowship yards)": "Область воздействия (Харизма ярдов)",
	"Line of sight": "Прямая видимость",
	"2 * Fellowship Bonus yards": "2 * (Рейтинг харизмы ярдов)",
	"You or Touch": "Персонаж или касание",
	"Intelligence yards": "Интеллект ярдов",
	"6 yards": "6 ярдов",
	"Fellowship yards": "Харизма ярдов",
	"Fellowship Bonus yards": "Рейтинг харизмы ярдов",
	"Initiative Bonus Miles": "Рейтинг инициативы миль",
	"Self": "Персонаж",
	"See text": "смотри текст",
	"24 yds": "24 ярда",
	"36 yds": "36 ярдов",
	"Fellowship Yards": "Харизма ярдов"
};

export const translatedSpellTarget = {
	"You": "Персонаж",
	"Special": "Особая",
	"AoE (Willpower Bonus yards)": "Область воздействия (Рейтинг силы воли ярдов)",
	"AoE (see description)": "Область воздействия (см. описание)",
	"AoE (Special)": "Область воздействия (особая)",
	"AoE (Initiative Bonus yards)": "Область воздействия (Рейтинг инициативы ярдов)",
	"AoE (Fellowship Bonus yards)": "Область воздействия (Рейтинг харизмы ярдов)",
	"AoE (a single location)": "Область воздействия (выбранное место)",
	"AoE (maximum, Willpower Bonus yards across)":
		"Область воздействия (не более Рейтинг силы воли ярдов в поперечнике)",
	"see description": "смотри описание",
	"a single location": "выбранное место",
	"Willpower Bonus yards across maximum": "не более Рейтинг силы воли ярдов в поперечнике",
	"1 (maximum)": "1 (максимум)",
	"2 × Initiative Bonus or Initiative Bonus Duration: Instant":
		"2 * Рейтинг инициативы или Рейтинг инициативы",
	"2 × Initiative Bonus or Initiative Bonus": "2 * Рейтинг инициативы или Рейтинг инициативы",
	"1 Forge": "1 кузнечный горн",
	"1 fire": "1 огонь",
	"1 with AoE (Willpower Bonus yards)": "1 с областью воздействия (Рейтинг силы воли ярдов)",
	"You or 1 (maximum)": "персонаж или 1 (максимум)",
	"1 object": "1 объект",
	"1 weapon": "1 оружие",
	"special": "особая",
	"1 object of 1 Encumbrance": "1 объект не более 1 Вес",
	"Willpower Bonus yards": "Рейтинг силы воли ярдов",
	"Fellowship Bonus": "Рейтинг харизмы ярдов",
	"Fellowship Bonus yards": "Рейтинг харизмы ярдов",
	"Initiative Bonus yards": "Рейтинг инициативы ярдов",
	"Initiative yards": "Инициатива ярдов",
	"2 * Willpower Bonus yards": "2 * Рейтинг силы воли ярдов",
	"4 * AoE (Willpower Bonus yards)": "4 * Область воздействия (Рейтинг силы воли ярдов)",
	"Willpower yards": "Сила воли ярдов",
	"Intelligence Bonus allies": "Рейтинг интеллекта ярдов",
	"Fellowship yards": "Харизма ярдов",
	"8 yards": "8 ярдов",
	"Fellowship Bonus allies": "Рейтинг харизмы союзников",
	"Fellowship yards": "Харизма ярдов",
	"Line of Sight": "Прямая видимость",
	"Any ally": "Любой союзник",
	"See text": "смотри текст",
	"Fellowship Bonus Yards": "Рейтинг харизмы ярдов"
};

export const translatedSpellDuration = {
	"Instant": "мгновенная",
	"Special": "особая",
	"Toughness Bonus Rounds": "Рейтинг выносливости раундов",
	"Willpower Bonus Rounds": "Рейтинг силы воли раундов",
	"Willpower Bonus rounds": "Рейтинг силы воли раундов",
	"Willpower Bonus Rounds+": "Рейтинг силы воли раундов +",
	"Willpower Bonus days": "Рейтинг силы воли дней",
	"Willpower Bonus Days": "Рейтинг силы воли дней",
	"Willpower Bonus hours": "Рейтинг силы воли часов",
	"Toughness Bonus hours": "Рейтинг выносливости часов",
	"Toughness Bonus minutes": "Рейтинг выносливости часов",
	"Willpower minutes": "Сила воли минут",
	"Willpower Minutes": "Сила воли минут",
	"Willpower Bonus minutes": "Рейтинг силы воли минут",
	"Willpower Days": "Сила воли дней",
	"Willpower days": "Сила воли дней",
	"1 Round": "1 раунд",
	"1 round": "1 раунд",
	"3 rounds": "3 раунда",
	"6 rounds": "6 раунда",
	"Initiative Bonus Rounds": "Рейтинг инициативы раундов",
	"Initiative Bonus rounds": "Рейтинг инициативы раундов",
	"Intelligence minutes": "Интеллект минут",
	"Target’s Intelligence Bonus Rounds": "Рейтинг интеллекта цели раундов",
	"Intelligence Bonus minutes": "Рейтинг интеллекта минут",
	"Until the next sunrise": "до рассвета",
	"Until sunrise - до рассвета": "до рассвета",
	"Initiative Bonus minutes": "Рейтинг инициативы минут",
	"1 hour": "1 час",
	"1 day": "1 день",
	"Fellowship Bonus rounds": "Рейтинг харизмы раундов",
	"Fellowship Bonus minutes": "Рейтинг харизмы минут",
	"Willpower Bonus hours, days, weeks, or months":
		"Рейтинг силы воли часов, дней, недель или месяцев",
	"Willpower Bonus minutes or days": "Рейтинг силы воли минут или дней",
	"Initiative minutes": "Инициатива минут",
	"Strength Bonus rounds": "Рейтинг силы раундов",
	"2 * Willpower Bonus rounds": "2 * Рейтинг силы воли раундов",
	"Willpower * 1d10 minutes": "Сила воли * 1d10 минут",
	"1d10 hours": "1d10 часов",
	"Willpower Bonus years": "Сила воли лет",
	"6 Rounds": "6 раундов",
	"Fellowship Bonus Rounds": "Рейтинг харизмы раундов",
	"1 Hour": "1 час",
	"Fellowship Bonus Hours (Special)": "Рейтинг харизмы часов (особое)",
	"Fellowship Bonus Hours": "Рейтинг харизмы часов",
	"Fellowship Bonus Minutes": "Рейтинг харизмы минут",
	"Agility Bonus Rounds": "Рейтинг проворства раундов",
	"Fellowship bonus Rounds": "Рейтинг харизмы раундов",
	"4 Rounds": "4 раунда",
	"3 Rounds": "3 раунда",
	"Immediate": "Мгновенно"
};

export const translatedSpellDamage = {
	"Willpower Bonus": "Рейтинг силы воли"
};

export const translatedGods = {
	Shallya: "Шалия",
	Ulric: "Ульрик",
	Taal: "Таал",
	Sigmar: "Сигмар",
	Ranald: "Ранальд",
	Rhya: "Райя",
	Morr: "Морр",
	Myrmidia: "Мирмидия",
	Manann: "Мананн",
	Verena: "Верена"
};
