name: Build and Release

on:
  push:
    branches:
      - v13
      - v14

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts"
          cache: true

      - name: Build
        run: vp build

      - name: Zip build output
        run: zip -r ru-ru.zip ru-ru

      - name: Create/Update Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ru-ru.zip
            public/module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
